CREATE TABLE BOOK (ID BIGINT NOT NULL, DESCRIPTION VARCHAR, ISBN VARCHAR, NBOFPAGE INTEGER, TITLE VARCHAR, UNITCOST DOUBLE, PRIMARY KEY (ID))
CREATE TABLE t_author (ID BIGINT NOT NULL, BIO VARCHAR(5000), date_of_birth DATE, first_name VARCHAR(64) NOT NULL, LANGUAGE INTEGER, last_name VARCHAR(64), PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
